name: 'Send Status'
description: 'Sends the status of a step to the meshcloud API'
inputs:
  step_id:
    description: 'The ID of the step'
    required: false
  status:
    description: 'The status of the step (SUCCEEDED or FAILED)'
    required: false
  user_message:
    description: 'The user message for a failed step'
    required: false
  system_message:
    description: 'The system message for a failed step'
    required: false
  final_status:
    description: 'The final status is the end-state of the run, combining all step outcomes into one status result based on your logic.'
    required: false
  summary:
    description: 'The summary message for the final status report'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'

