name: 'Send Status'
description: 'Sends the status of a step to the meshcloud API'
inputs:
  step_id:
    description: 'The ID of the step'
    required: true
  status:
    description: 'The status of the step (SUCCEEDED or FAILED)'
    required: true
  user_message:
    description: 'The user message for a failed step'
    required: false
  system_message:
    description: 'The system message for a failed step'
    required: false
  is_final:
    description: 'Indicates if this is the final status report'
    required: false
    default: 'false'
  summary:
    description: 'The summary message for the final status report'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'

