name: 'Send Status'
description: 'Sends the status of a step to the meshcloud API'
inputs:
  step_id:
    description: 'The ID of the step'
    required: false
  step_status:
    description: 'The status of the step (IN_PROGRESS, SUCCEEDED or FAILED)'
    required: false
  user_message:
    description: 'The user message for a failed step'
    required: false
  system_message:
    description: 'The system message for a failed step'
    required: false
  run_status:
    description: 'The final status of the run. Sending this to a terminate status like SUCCEEDED or FAILED signals to meshStack that the run is complete. Send this only once.'
    required: false
  outputs:_json:
    description: 'A json objects with outputs of the step. All outputs in a run will be merged by meshStack.
runs:
  using: 'node20'
  main: 'dist/index.js'

