name: Test Action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Meshstack Authentication
        id: setup-meshstack-auth 
        uses: meshcloud/actions-meshstack-auth@main
        with:
          base_url: https://federation.demo.meshcloud.io
          client_id: ${{ secrets.CLIENT_ID }}
          key_secret: ${{ secrets.KEY_SECRET }}

      - name: Run Action
        id: run-action
        uses: ./
        with:
          final_status: "SUCCEEDED"
          user_message: 'User message'
          system_message: 'System message'
          summary: 'Summary message'

      - name: Display temp directory
        run: echo "Temporary directory is ${{ steps.run-action.outputs.temp_directory }}"

