name: Test Action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy meshstack_token.json to temp directory
        run: |
          mkdir -p $RUNNER_TEMP
          cp test_data/meshstack_token.json $RUNNER_TEMP/meshstack_token.json

      
      - name: Setup Meshstack Authentication
        id: setup-meshstack-auth 
        uses: meshcloud/actions-register-source@main
        with:
          steps: |
            [
              { "id": "terraform-validate", "displayName": "terraform validate" },
              { "id": "terraform-plan", "displayName": "terraform plan" },
              { "id": "terraform-apply", "displayName": "terraform apply" }
            ]
          client_id: ${{ secrets.CLIENT_ID }}
          key_secret: ${{ secrets.KEY_SECRET }}

      - name: Run Action
        id: run-action
        uses: ./
        with:
          step_id: 'terrafrom-validate'
          status: 'SUCCESS'
          user_message: 'User message'
          system_message: 'System message'
          summary: 'Summary message'

      - name: Display temp directory
        run: echo "Temporary directory is ${{ steps.run-action.outputs.temp_directory }}"

